### ISSUE TITLE
Gas reporting for rkyv migration

### ISSUE THREAD

**Issue by miloszm** [dusk-network/rusk-vm#280] opened 2021-12-23 10:16 UTC
**Describe what you want implemented** 
Gas report for a rusk-vm contract

**Describe "Why" this is needed**
We want to compare the cost of offset passing as contract call param vs in-memory offset

**Describe alternatives you've considered**
N/A

**Additional context**
This needs to be done for only one contract

**Comment by autholykos** [comment] 2022-05-09 10:27
Duplicate of #322

**Closed by autholykos** 2022-05-09 10:27 UTC
Labels: type:feature, team:Core, mark:next
